AWSTemplateFormatVersion: 2010-09-09
Resources:
  UluruVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/21
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Environment
          Value: UluruTest
  UluruSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: UluruVPC
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/28
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: UluruSubnet
  UluruEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  UluruInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: UluruInternetGateway
  UluruVPCIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: UluruVPC
      InternetGatewayId:
        Ref: UluruInternetGateway
Outputs:
  UluruSubnet:
    Value:
      Ref: UluruSubnet
    Export:
      Name: UluruSubnet
  UluruAllocationId:
    Value:
      Fn::GetAtt: ["UluruEIP", "AllocationId"]
    Export:
      Name: UluruAllocationId
